version: '2'
services:
    confkit-app:
        image: confkit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://confkit-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=confkit
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    confkit-mongodb:
        extends:
            file: mongodb.yml
            service: confkit-mongodb
